### ISSUE TITLE
Swift 4 compatibility

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#585]
I've identified a handful of issues trying to build SwiftProtobuf with the current Swift 4 development snapshots.  We do of course want to be compatible with Swift 4 when it ships, so most of these we'll probably have to fix.

- [x] `withExtendedLifetime` tuple deconstruction should be more explicit (addressed in #582)
- [x] String slices need to be explicitly converted to String (addressed in #582)
- [x] Public functions seem to want public default values (changed in an early draft of #582 but backed out until we figure out how to best address this)
- [x] SR-4218 leads to test failures on Linux for JSON and TextFormat strings with control characters (we disabled these tests on Linux for Swift 3 and were hoping to reenable the tests as soon as this bug was fixed -- disabled again in #611 for Swift 4.0)
- [x] Should use `String(decoding:as:)` to convert UTF-8 to String -- this is faster than the `NSString` initializer we used with Swift 3 and seems to work consistently on Linux and macOS. (addressed in #584)
- [x] `truncatingBitPattern:` was renamed in Swift 4 (addressed in #611)

**Comment by tbkka** [comment]
PR #611 addresses the still-broken SR4218 issue and the name change for `truncatingBitPattern`.  This gets us very close to being able to build with either Swift 3 or 4 from the same source.

**Comment by tbkka** [comment]
So at this point, I think only the default argument problem remains to get something that builds with the current Swift 4 development snapshots.

I asked the Swift folks, and they said that in the future, they want to inline default arguments at the caller, which requires them to be public.  So we could either expose the necessary symbol or repeat the literal string.  I think there is only one public function that uses that symbol as a default right now, so I don't think it makes a big difference either way.

**Comment by thomasvl** [comment]
Yea, go ahead and make the constant public given the direction they are going.

**Comment by tbkka** [comment]
PR #612 implements this.  It also addresses a couple of other issues -- compatibility with older Swift compilers on Linux, and an ambiguity that was flagged as a warning in the new compilers.

**Comment by tbkka** [comment]
I believe we've now resolved all the oustanding issues with Swift 4 per se.

I'll close this.  (I'm also going to look separately at #610.)
